# Generated by Django 3.2.18 on 2024-01-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutclass',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
